# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Zhangshi/Desktop/risc-v-oppenyes/my_e203/ip/mmcm/mmcm.xci
# IP: The module: 'mmcm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Zhangshi/Desktop/project_5.gen/sources_1/ip/mmcm/mmcm_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Zhangshi/Desktop/project_5.gen/sources_1/ip/mmcm/mmcm.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Zhangshi/Desktop/project_5.gen/sources_1/ip/mmcm/mmcm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Zhangshi/Desktop/risc-v-oppenyes/my_e203/ip/mmcm/mmcm.xci
# IP: The module: 'mmcm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Zhangshi/Desktop/project_5.gen/sources_1/ip/mmcm/mmcm_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Zhangshi/Desktop/project_5.gen/sources_1/ip/mmcm/mmcm.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Zhangshi/Desktop/project_5.gen/sources_1/ip/mmcm/mmcm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
